apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: transactions.raw
  namespace: edl-data
  labels:
    strimzi.io/cluster: edl-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: transactions.curated
  namespace: edl-data
  labels:
    strimzi.io/cluster: edl-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 86400000
