apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Namespace
      name: edl-data
    patch: |-
      - op: add
        path: /metadata/labels/openshift.io~1cluster-monitoring
        value: "false"
