apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: edl-data
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: "1"
        memory: 1Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: edl-platform
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 500m
        memory: 512Mi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-container-limits
  namespace: edl-observability
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 1Gi
