apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: data-workload-reader
  namespace: edl-data
rules:
  - apiGroups: [""]
    resources: ["pods","services","configmaps"]
    verbs: ["get","list","watch"]
  - apiGroups: ["apps"]
    resources: ["deployments","statefulsets"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: data-workload-reader
  namespace: edl-data
subjects:
  - kind: ServiceAccount
    name: data-workload
    namespace: edl-data
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: data-workload-reader
