apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-operator
  namespace: edl-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-workload
  namespace: edl-data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-reader
  namespace: edl-observability
