admissionController:
  replicas: 1
  container:
    resources:
      requests: {cpu: 100m, memory: 128Mi}
      limits: {cpu: '1', memory: 512Mi}
backgroundController:
  replicas: 1
  resources:
    requests: {cpu: 50m, memory: 64Mi}
    limits: {cpu: 500m, memory: 256Mi}
cleanupController:
  replicas: 1
  resources:
    requests: {cpu: 50m, memory: 64Mi}
    limits: {cpu: 500m, memory: 256Mi}
reportsController:
  replicas: 1
  resources:
    requests: {cpu: 50m, memory: 64Mi}
    limits: {cpu: 500m, memory: 256Mi}
