apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: edl-kafka-metrics
  namespace: edl-data
  labels:
    app.kubernetes.io/part-of: enterprise-data-lakehouse
spec:
  selector:
    matchExpressions:
      - key: strimzi.io/kind
        operator: In
        values:
          - Kafka
  namespaceSelector:
    matchNames:
      - edl-data
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
      interval: 30s
      scrapeTimeout: 10s
      relabelings:
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(strimzi_io_.+)
          replacement: $1
        - sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: namespace
        - sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: kubernetes_pod_name
